-- Script manual para crear las tablas de Configuracion Contable.
-- No fue ejecutado por Codex. Revisar y aplicar manualmente si corresponde.

create table if not exists public.configuraciones_contables (
    id integer generated by default as identity primary key,
    codigo_operacion character varying(100) not null,
    descripcion character varying(500) not null,
    activa boolean not null default true,
    fecha_alta timestamp with time zone not null,
    usuario_alta character varying(100) not null
);

create unique index if not exists ix_configuraciones_contables_codigo_operacion
    on public.configuraciones_contables using btree (codigo_operacion);

create table if not exists public.configuraciones_contables_detalle (
    id integer generated by default as identity primary key,
    configuracion_contable_id integer not null,
    tipo_movimiento character varying(10) not null,
    concepto character varying(100) not null,
    cuenta_contable_id integer not null,
    orden integer not null,
    activo boolean not null default true,
    constraint fk_configuraciones_contables_detalle_configuracion
        foreign key (configuracion_contable_id)
        references public.configuraciones_contables(id)
        on delete restrict,
    constraint fk_configuraciones_contables_detalle_cuenta
        foreign key (cuenta_contable_id)
        references public.cuentas_contables(id)
        on delete restrict
);

create index if not exists ix_configuraciones_contables_detalle_configuracion_contable_id
    on public.configuraciones_contables_detalle using btree (configuracion_contable_id);

create index if not exists ix_configuraciones_contables_detalle_cuenta_contable_id
    on public.configuraciones_contables_detalle using btree (cuenta_contable_id);

create unique index if not exists ix_configuraciones_contables_detalle_concepto_activo
    on public.configuraciones_contables_detalle using btree (configuracion_contable_id, concepto)
    where activo = true;
