-- Recrea la tabla cabecera acuerdos_comerciales.
-- Ejecutar sobre PostgreSQL en la base del sistema.
--
-- Importante:
-- Si la tabla fue eliminada, los datos originales de cabecera no se pueden recuperar
-- desde este script salvo que existan tablas hijas con referencias. En ese caso se
-- crean cabeceras minimas con numero_acuerdo = 'RECUPERAR-{id}' para permitir
-- volver a levantar las FK y luego corregir los datos manualmente.

BEGIN;

CREATE TABLE IF NOT EXISTS acuerdos_comerciales (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cliente_externo_id text NOT NULL,
    obra_externa_id text NOT NULL,
    numero_acuerdo text NOT NULL,
    fecha_acuerdo timestamp with time zone NOT NULL,
    descripcion text NULL,
    monto_total numeric NOT NULL,
    estado integer NOT NULL,
    via_operacion integer NOT NULL,
    observaciones text NULL,
    fecha_alta timestamp with time zone NOT NULL,
    usuario_alta text NOT NULL,
    CONSTRAINT "PK_acuerdos_comerciales" PRIMARY KEY (id)
);

-- Reconstruccion minima desde tablas hijas, si quedaron registros.
WITH referenced_ids AS (
    SELECT acuerdo_comercial_id AS id
    FROM acuerdos_comerciales_vias
    WHERE to_regclass('public.acuerdos_comerciales_vias') IS NOT NULL
    UNION
    SELECT acuerdo_comercial_id AS id
    FROM pagos_comerciales
    WHERE to_regclass('public.pagos_comerciales') IS NOT NULL
    UNION
    SELECT acuerdo_comercial_id AS id
    FROM ajustes_cuotas_comerciales
    WHERE to_regclass('public.ajustes_cuotas_comerciales') IS NOT NULL
    UNION
    SELECT acuerdo_comercial_id AS id
    FROM ajustes_acuerdos_comerciales_vias
    WHERE to_regclass('public.ajustes_acuerdos_comerciales_vias') IS NOT NULL
),
base AS (
    SELECT
        r.id,
        COALESCE(MAX(p.cliente_externo_id), 'RECUPERAR') AS cliente_externo_id,
        COALESCE(MAX(p.obra_externa_id), 'RECUPERAR') AS obra_externa_id,
        'RECUPERAR-' || r.id::text AS numero_acuerdo,
        COALESCE(MIN(v.fecha_alta), MIN(p.fecha_pago), now()) AS fecha_acuerdo,
        SUM(COALESCE(v.monto_actual, 0)) AS monto_total,
        COALESCE(MIN(v.estado), 0) AS estado,
        COALESCE(MIN(v.via_operacion), 0) AS via_operacion,
        MAX(v.observaciones) AS observaciones,
        COALESCE(MIN(v.fecha_alta), now()) AS fecha_alta,
        COALESCE(MAX(v.usuario_alta), 'sistema') AS usuario_alta
    FROM referenced_ids r
    LEFT JOIN acuerdos_comerciales_vias v ON v.acuerdo_comercial_id = r.id
    LEFT JOIN pagos_comerciales p ON p.acuerdo_comercial_id = r.id
    GROUP BY r.id
)
INSERT INTO acuerdos_comerciales (
    id,
    cliente_externo_id,
    obra_externa_id,
    numero_acuerdo,
    fecha_acuerdo,
    descripcion,
    monto_total,
    estado,
    via_operacion,
    observaciones,
    fecha_alta,
    usuario_alta
)
SELECT
    id,
    cliente_externo_id,
    obra_externa_id,
    numero_acuerdo,
    fecha_acuerdo,
    'Cabecera reconstruida automaticamente. Revisar datos originales.' AS descripcion,
    monto_total,
    estado,
    via_operacion,
    observaciones,
    fecha_alta,
    usuario_alta
FROM base
ON CONFLICT (id) DO NOTHING;

-- Ajusta la secuencia identity para que los proximos inserts no pisen ids reconstruidos.
SELECT setval(
    pg_get_serial_sequence('acuerdos_comerciales', 'id'),
    GREATEST(COALESCE((SELECT MAX(id) FROM acuerdos_comerciales), 0), 1),
    true
);

-- Reponer foreign keys si fueron eliminadas por DROP TABLE ... CASCADE.
DO $$
BEGIN
    IF to_regclass('public.acuerdos_comerciales_vias') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_acuerdos_comerciales_vias_acuerdos_comerciales_acuerdo_come~') THEN
        ALTER TABLE acuerdos_comerciales_vias
            ADD CONSTRAINT "FK_acuerdos_comerciales_vias_acuerdos_comerciales_acuerdo_come~"
            FOREIGN KEY (acuerdo_comercial_id)
            REFERENCES acuerdos_comerciales (id)
            ON DELETE CASCADE;
    END IF;

    IF to_regclass('public.pagos_comerciales') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_pagos_comerciales_acuerdos_comerciales_acuerdo_comercial_id') THEN
        ALTER TABLE pagos_comerciales
            ADD CONSTRAINT "FK_pagos_comerciales_acuerdos_comerciales_acuerdo_comercial_id"
            FOREIGN KEY (acuerdo_comercial_id)
            REFERENCES acuerdos_comerciales (id)
            ON DELETE CASCADE;
    END IF;

    IF to_regclass('public.ajustes_cuotas_comerciales') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ajustes_cuotas_comerciales_acuerdos_comerciales_acuerdo_com~') THEN
        ALTER TABLE ajustes_cuotas_comerciales
            ADD CONSTRAINT "FK_ajustes_cuotas_comerciales_acuerdos_comerciales_acuerdo_com~"
            FOREIGN KEY (acuerdo_comercial_id)
            REFERENCES acuerdos_comerciales (id)
            ON DELETE CASCADE;
    END IF;

    IF to_regclass('public.ajustes_acuerdos_comerciales_vias') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ajustes_acuerdos_comerciales_vias_acuerdos_comerciales_acue~') THEN
        ALTER TABLE ajustes_acuerdos_comerciales_vias
            ADD CONSTRAINT "FK_ajustes_acuerdos_comerciales_vias_acuerdos_comerciales_acue~"
            FOREIGN KEY (acuerdo_comercial_id)
            REFERENCES acuerdos_comerciales (id)
            ON DELETE CASCADE;
    END IF;
END $$;

COMMIT;
