// <auto-generated />
using System;
using BudgetControl.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetControl.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711174258_InitialSalesHeaderModule")]
    partial class InitialSalesHeaderModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetControl.Api.Models.Accounting.AsientoContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsAutomatico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_automatico");

                    b.Property<bool>("EsReversion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_reversion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<int?>("IdAsientoRevertido")
                        .HasColumnType("integer")
                        .HasColumnName("id_asiento_revertido");

                    b.Property<string>("IdOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_origen");

                    b.Property<string>("ModuloOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modulo_origen");

                    b.Property<string>("UsuarioAlta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_alta");

                    b.HasKey("Id");

                    b.HasIndex("IdAsientoRevertido")
                        .HasDatabaseName("ix_asientos_contables_id_asiento_revertido");

                    b.HasIndex("ModuloOrigen", "IdOrigen")
                        .HasDatabaseName("ix_asientos_contables_modulo_origen_id_origen");

                    b.ToTable("asientos_contables", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Accounting.AsientoContableDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AsientoContableId")
                        .HasColumnType("integer")
                        .HasColumnName("asiento_contable_id");

                    b.Property<int>("CuentaContableId")
                        .HasColumnType("integer")
                        .HasColumnName("cuenta_contable_id");

                    b.Property<decimal>("Debe")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("debe");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("Haber")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("haber");

                    b.HasKey("Id");

                    b.HasIndex("AsientoContableId")
                        .HasDatabaseName("ix_asientos_contables_detalle_asiento_contable_id");

                    b.HasIndex("CuentaContableId")
                        .HasDatabaseName("ix_asientos_contables_detalle_cuenta_contable_id");

                    b.ToTable("asientos_contables_detalle", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Accounting.ConfiguracionContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("CodigoOperacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_operacion");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("UsuarioAlta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_alta");

                    b.HasKey("Id");

                    b.HasIndex("CodigoOperacion")
                        .IsUnique()
                        .HasDatabaseName("ix_configuraciones_contables_codigo_operacion");

                    b.ToTable("configuraciones_contables", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Accounting.ConfiguracionContableDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("concepto");

                    b.Property<int>("ConfiguracionContableId")
                        .HasColumnType("integer")
                        .HasColumnName("configuracion_contable_id");

                    b.Property<int>("CuentaContableId")
                        .HasColumnType("integer")
                        .HasColumnName("cuenta_contable_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo_movimiento");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionContableId")
                        .HasDatabaseName("ix_configuraciones_contables_detalle_configuracion_contable_id");

                    b.HasIndex("CuentaContableId")
                        .HasDatabaseName("ix_configuraciones_contables_detalle_cuenta_contable_id");

                    b.HasIndex("ConfiguracionContableId", "Concepto")
                        .IsUnique()
                        .HasDatabaseName("ix_configuraciones_contables_detalle_concepto_activo")
                        .HasFilter("activo = true");

                    b.ToTable("configuraciones_contables_detalle", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Accounting.CuentaContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_cuenta");

                    b.Property<string>("UsuarioAlta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_alta");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_cuentas_contables_codigo");

                    b.ToTable("cuentas_contables", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AcuerdoComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteExternoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cliente_externo_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAcuerdo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_acuerdo");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_total");

                    b.Property<string>("NumeroAcuerdo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_acuerdo");

                    b.Property<string>("ObraExternaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("obra_externa_id");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("UsuarioAlta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_alta");

                    b.Property<int>("ViaOperacion")
                        .HasColumnType("integer")
                        .HasColumnName("via_operacion");

                    b.HasKey("Id");

                    b.ToTable("acuerdos_comerciales", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcuerdoComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<int>("ModalidadCobro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("modalidad_cobro");

                    b.Property<string>("MonedaCodigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("moneda_codigo");

                    b.Property<decimal>("MontoActual")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_actual");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_original");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("UsuarioAlta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_alta");

                    b.Property<int>("ViaOperacion")
                        .HasColumnType("integer")
                        .HasColumnName("via_operacion");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoComercialId", "ViaOperacion")
                        .IsUnique();

                    b.ToTable("acuerdos_comerciales_vias", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AjusteAcuerdoComercialVia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcuerdoComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_id");

                    b.Property<int>("AcuerdoComercialViaId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_via_id");

                    b.Property<decimal>("Diferencia")
                        .HasColumnType("numeric")
                        .HasColumnName("diferencia");

                    b.Property<DateTime>("FechaAjuste")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ajuste");

                    b.Property<string>("MonedaCodigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("moneda_codigo");

                    b.Property<decimal>("MontoAnterior")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_anterior");

                    b.Property<decimal>("MontoNuevo")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_nuevo");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<int>("TipoAjuste")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_ajuste");

                    b.Property<string>("UsuarioAjuste")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_ajuste");

                    b.Property<int>("ViaOperacion")
                        .HasColumnType("integer")
                        .HasColumnName("via_operacion");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoComercialId");

                    b.HasIndex("AcuerdoComercialViaId");

                    b.ToTable("ajustes_acuerdos_comerciales_vias", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AjusteCuotaComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcuerdoComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_id");

                    b.Property<int>("AcuerdoComercialViaId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_via_id");

                    b.Property<int>("CuotaComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("cuota_comercial_id");

                    b.Property<DateTime>("FechaAjuste")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ajuste");

                    b.Property<DateTime?>("FechaVencimientoAnterior")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento_anterior");

                    b.Property<DateTime?>("FechaVencimientoNueva")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento_nueva");

                    b.Property<decimal?>("ImporteAnterior")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_anterior");

                    b.Property<decimal?>("ImporteNuevo")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_nuevo");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<int>("PlanPagoId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_pago_id");

                    b.Property<int>("TipoAjuste")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_ajuste");

                    b.Property<string>("UsuarioAjuste")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_ajuste");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoComercialId");

                    b.HasIndex("AcuerdoComercialViaId");

                    b.HasIndex("CuotaComercialId");

                    b.HasIndex("PlanPagoId");

                    b.ToTable("ajustes_cuotas_comerciales", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AplicacionPagoComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CuotaComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("cuota_comercial_id");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_aplicacion");

                    b.Property<int?>("HitoComercialViaId")
                        .HasColumnType("integer")
                        .HasColumnName("hito_comercial_via_id");

                    b.Property<decimal>("ImporteAplicado")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_aplicado");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("PagoComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("pago_comercial_id");

                    b.Property<int>("TipoImputacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("tipo_imputacion");

                    b.Property<string>("UsuarioAplicacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_aplicacion");

                    b.HasKey("Id");

                    b.HasIndex("CuotaComercialId");

                    b.HasIndex("HitoComercialViaId");

                    b.HasIndex("PagoComercialId");

                    b.ToTable("aplicaciones_pago_comerciales", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.ClienteReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("ClienteExternoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cliente_externo_id");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("documento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("clientes_referencia", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.CuotaComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<decimal>("ImporteOriginal")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_original");

                    b.Property<decimal>("ImportePagado")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_pagado");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("integer")
                        .HasColumnName("numero_cuota");

                    b.Property<int>("PlanPagoId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_pago_id");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_pendiente");

                    b.Property<int>("TipoCuota")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_cuota");

                    b.HasKey("Id");

                    b.HasIndex("PlanPagoId");

                    b.ToTable("cuotas_comerciales", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.HitoComercialVia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcuerdoComercialViaId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_via_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime>("FechaReferencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_referencia");

                    b.Property<decimal>("ImporteAplicado")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_aplicado");

                    b.Property<decimal>("ImporteEstimado")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_estimado");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("UsuarioAlta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_alta");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoComercialViaId");

                    b.ToTable("hitos_comerciales_vias", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.ObraReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("ClienteExternoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cliente_externo_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreObra")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_obra");

                    b.Property<string>("ObraExternaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("obra_externa_id");

                    b.HasKey("Id");

                    b.ToTable("obras_referencia", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.PagoComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcuerdoComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_id");

                    b.Property<int>("AcuerdoComercialViaId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_via_id");

                    b.Property<string>("ClienteExternoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cliente_externo_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<decimal>("ImporteTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_total");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("medio_pago");

                    b.Property<string>("MonedaCodigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("moneda_codigo");

                    b.Property<string>("ObraExternaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("obra_externa_id");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("OrigenPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("origen_pago");

                    b.Property<int>("TipoImputacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("tipo_imputacion");

                    b.Property<string>("UsuarioAlta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_alta");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoComercialId");

                    b.HasIndex("AcuerdoComercialViaId");

                    b.ToTable("pagos_comerciales", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.PlanPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcuerdoComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_id");

                    b.Property<int>("AcuerdoComercialViaId")
                        .HasColumnType("integer")
                        .HasColumnName("acuerdo_comercial_via_id");

                    b.Property<int>("CantidadCuotas")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_cuotas");

                    b.Property<DateTime>("FechaPrimerVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_primer_vencimiento");

                    b.Property<decimal>("MontoAnticipo")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_anticipo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("Periodicidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("periodicidad");

                    b.Property<bool>("TieneAnticipo")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_anticipo");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoComercialViaId")
                        .IsUnique();

                    b.ToTable("planes_pago", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.VinculacionFacturaComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CuotaComercialId")
                        .HasColumnType("integer")
                        .HasColumnName("cuota_comercial_id");

                    b.Property<string>("FacturaExternaId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("factura_externa_id");

                    b.Property<DateTime>("FechaVinculacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vinculacion");

                    b.Property<decimal>("ImporteVinculado")
                        .HasColumnType("numeric")
                        .HasColumnName("importe_vinculado");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_factura");

                    b.HasKey("Id");

                    b.HasIndex("CuotaComercialId");

                    b.ToTable("vinculaciones_factura_comerciales", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Sales.TipoComprobanteVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Letra")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("letra");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("Signo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("signo");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_tipos_comprobante_venta_codigo");

                    b.ToTable("tipos_comprobante_venta", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "FACTURA_A",
                            Descripcion = "Factura A",
                            Letra = "A",
                            Orden = 10,
                            Signo = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "FACTURA_B",
                            Descripcion = "Factura B",
                            Letra = "B",
                            Orden = 20,
                            Signo = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "FACTURA_C",
                            Descripcion = "Factura C",
                            Letra = "C",
                            Orden = 30,
                            Signo = 1
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Codigo = "NOTA_DEBITO",
                            Descripcion = "Nota de debito",
                            Orden = 40,
                            Signo = 1
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Codigo = "NOTA_CREDITO",
                            Descripcion = "Nota de credito",
                            Orden = 50,
                            Signo = -1
                        });
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Sales.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteExternoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cliente_externo_id");

                    b.Property<decimal>("Cotizacion")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cotizacion");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime>("FechaComprobante")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_comprobante");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("MonedaCodigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("moneda_codigo");

                    b.Property<long>("NumeroComprobante")
                        .HasColumnType("bigint")
                        .HasColumnName("numero_comprobante");

                    b.Property<string>("ObraExternaId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("obra_externa_id");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observaciones");

                    b.Property<int>("PuntoVenta")
                        .HasColumnType("integer")
                        .HasColumnName("punto_venta");

                    b.Property<int>("TipoComprobanteVentaId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_comprobante_venta_id");

                    b.Property<string>("UsuarioAlta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_alta");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id");

                    b.HasIndex("ClienteExternoId")
                        .HasDatabaseName("ix_ventas_cliente_externo_id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_ventas_estado");

                    b.HasIndex("FechaComprobante")
                        .HasDatabaseName("ix_ventas_fecha_comprobante");

                    b.HasIndex("ObraExternaId")
                        .HasDatabaseName("ix_ventas_obra_externa_id");

                    b.HasIndex("TipoComprobanteVentaId", "PuntoVenta", "NumeroComprobante")
                        .IsUnique()
                        .HasDatabaseName("ix_ventas_numeracion");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Accounting.AsientoContable", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Accounting.AsientoContable", "AsientoRevertido")
                        .WithMany("Reversiones")
                        .HasForeignKey("IdAsientoRevertido")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AsientoRevertido");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Accounting.AsientoContableDetalle", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Accounting.AsientoContable", "AsientoContable")
                        .WithMany("Detalles")
                        .HasForeignKey("AsientoContableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetControl.Api.Models.Accounting.CuentaContable", "CuentaContable")
                        .WithMany()
                        .HasForeignKey("CuentaContableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsientoContable");

                    b.Navigation("CuentaContable");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Accounting.ConfiguracionContableDetalle", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Accounting.ConfiguracionContable", "ConfiguracionContable")
                        .WithMany("Detalles")
                        .HasForeignKey("ConfiguracionContableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetControl.Api.Models.Accounting.CuentaContable", "CuentaContable")
                        .WithMany()
                        .HasForeignKey("CuentaContableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfiguracionContable");

                    b.Navigation("CuentaContable");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercial", "AcuerdoComercial")
                        .WithMany("Vias")
                        .HasForeignKey("AcuerdoComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcuerdoComercial");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AjusteAcuerdoComercialVia", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercial", "AcuerdoComercial")
                        .WithMany()
                        .HasForeignKey("AcuerdoComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", "AcuerdoComercialVia")
                        .WithMany("Ajustes")
                        .HasForeignKey("AcuerdoComercialViaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcuerdoComercial");

                    b.Navigation("AcuerdoComercialVia");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AjusteCuotaComercial", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercial", "AcuerdoComercial")
                        .WithMany()
                        .HasForeignKey("AcuerdoComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", "AcuerdoComercialVia")
                        .WithMany()
                        .HasForeignKey("AcuerdoComercialViaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetControl.Api.Models.Commercial.CuotaComercial", "CuotaComercial")
                        .WithMany("Ajustes")
                        .HasForeignKey("CuotaComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetControl.Api.Models.Commercial.PlanPago", "PlanPago")
                        .WithMany()
                        .HasForeignKey("PlanPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcuerdoComercial");

                    b.Navigation("AcuerdoComercialVia");

                    b.Navigation("CuotaComercial");

                    b.Navigation("PlanPago");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AplicacionPagoComercial", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.CuotaComercial", "CuotaComercial")
                        .WithMany("Aplicaciones")
                        .HasForeignKey("CuotaComercialId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BudgetControl.Api.Models.Commercial.HitoComercialVia", "HitoComercialVia")
                        .WithMany("Aplicaciones")
                        .HasForeignKey("HitoComercialViaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BudgetControl.Api.Models.Commercial.PagoComercial", "PagoComercial")
                        .WithMany("Aplicaciones")
                        .HasForeignKey("PagoComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuotaComercial");

                    b.Navigation("HitoComercialVia");

                    b.Navigation("PagoComercial");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.CuotaComercial", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.PlanPago", "PlanPago")
                        .WithMany("Cuotas")
                        .HasForeignKey("PlanPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPago");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.HitoComercialVia", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", "AcuerdoComercialVia")
                        .WithMany("Hitos")
                        .HasForeignKey("AcuerdoComercialViaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcuerdoComercialVia");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.PagoComercial", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercial", "AcuerdoComercial")
                        .WithMany("Pagos")
                        .HasForeignKey("AcuerdoComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", "AcuerdoComercialVia")
                        .WithMany("Pagos")
                        .HasForeignKey("AcuerdoComercialViaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcuerdoComercial");

                    b.Navigation("AcuerdoComercialVia");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.PlanPago", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", "AcuerdoComercialVia")
                        .WithOne("PlanPago")
                        .HasForeignKey("BudgetControl.Api.Models.Commercial.PlanPago", "AcuerdoComercialViaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcuerdoComercialVia");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.VinculacionFacturaComercial", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Commercial.CuotaComercial", "CuotaComercial")
                        .WithMany("VinculacionesFactura")
                        .HasForeignKey("CuotaComercialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuotaComercial");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Sales.Venta", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Sales.TipoComprobanteVenta", "TipoComprobante")
                        .WithMany("Ventas")
                        .HasForeignKey("TipoComprobanteVentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoComprobante");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.UserRole", b =>
                {
                    b.HasOne("BudgetControl.Api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetControl.Api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Accounting.AsientoContable", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Reversiones");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Accounting.ConfiguracionContable", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AcuerdoComercial", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("Vias");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.AcuerdoComercialVia", b =>
                {
                    b.Navigation("Ajustes");

                    b.Navigation("Hitos");

                    b.Navigation("Pagos");

                    b.Navigation("PlanPago");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.CuotaComercial", b =>
                {
                    b.Navigation("Ajustes");

                    b.Navigation("Aplicaciones");

                    b.Navigation("VinculacionesFactura");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.HitoComercialVia", b =>
                {
                    b.Navigation("Aplicaciones");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.PagoComercial", b =>
                {
                    b.Navigation("Aplicaciones");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Commercial.PlanPago", b =>
                {
                    b.Navigation("Cuotas");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.Sales.TipoComprobanteVenta", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("BudgetControl.Api.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
